variants:
    generic:
        
            uses:
                swfw_soc_shar: &alias_swfw_soc_shar
                    release: "1.4"
                    variant: generic
                swfw_shared_ti: &swfw_shared_ti
                    release: "1.5"
                    variant: generic